# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
                ('comment_nums', models.CharField(max_length=20)),
            ],
        ),
    ]
