# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 01:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_blogdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdatabase',
            name='dummy',
            field=models.CharField(default=datetime.datetime(2016, 5, 15, 1, 9, 37, 909088, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
